name: medicaid_transfer_learning
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - statsmodels=0.14.0
  - pyyaml=6.0.1
  - tqdm=4.65.0
  - jupyter=1.0.0
  - pytest=7.4.0
  - pip
  - pip:
    - pingouin==0.5.3
    - lifelines==0.27.7
    - numba==0.57.1

