# Model Configuration for Transfer Learning Analysis

# Random seeds for reproducibility
random_seeds:
  model_init: 42
  data_split: 123
  bootstrap: 456

# Cross-validation settings
cross_validation:
  n_folds: 5
  stratified: true
  shuffle: true

# Bootstrap settings
bootstrap:
  n_iterations: 1000
  confidence_level: 0.95

# Model hyperparameters
models:
  source_only:
    type: "LogisticRegression"
    C: 1.0
    max_iter: 1000
    solver: "liblinear"
    
  prototypical_networks:
    embedding_dim: 128
    n_support: 5
    distance_metric: "euclidean"
    learning_rate: 0.001
    n_epochs: 100
    
  maml:
    inner_lr: 0.01
    outer_lr: 0.001
    n_inner_steps: 5
    first_order: true
    support_query_split: 0.8
    n_epochs: 100
    
  domain_adversarial:
    feature_extractor_dims: [128, 64, 32]
    domain_classifier_dims: [64, 32]
    lambda_domain: 0.1
    learning_rate: 0.001
    n_epochs: 100
    
  causal_transfer:
    propensity_model: "LogisticRegression"
    causal_features: ["age", "gender", "comorbidity_index"]
    backdoor_adjustment: true
    
  tabtransformer:
    n_heads: 8
    n_layers: 4
    embedding_dim: 64
    hidden_dim: 256
    dropout: 0.1
    learning_rate: 0.001
    n_epochs: 100
    
  meta_ensemble:
    meta_learner_dims: [64, 32]
    temperature_scaling: true
    learning_rate: 0.001
    n_epochs: 50

# Optimization settings
optimization:
  early_stopping:
    patience: 10
    min_delta: 0.001
  
  learning_rate_scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.5
    patience: 5
    
# Evaluation settings
evaluation:
  metrics:
    - "auc"
    - "youdens_j"
    - "sensitivity"
    - "specificity"
    - "nnt"
    - "brier_score"
    - "calibration_error"
  
  statistical_tests:
    multiple_comparison_method: "holm"
    significance_level: 0.05
    effect_size_threshold: 0.02  # Clinical significance threshold for AUC
    
# Calibration settings
calibration:
  methods:
    - "platt_scaling"
    - "isotonic_regression"
  n_bins: 10
  
# Ablation study settings
ablation:
  feature_categories:
    - "clinical"
    - "demographics" 
    - "healthcare_utilization"
    - "geographic"
    - "insurance"
    - "temporal"
  
  model_components:
    - "meta_learning_adaptation"
    - "domain_adversarial_loss"
    - "feature_alignment"
    - "temporal_stability"

